from sqlalchemy import Column, Integer, String, Float, Boolean, DateTime
from api.database import Base

class Delivery(Base):
    __tablename__ = "deliveries"
    id = Column(Integer, primary_key=True, index=True)
    vehicle_id = Column(Integer)
    driver_id = Column(Integer)
    scheduled_time = Column(DateTime)
    actual_time = Column(DateTime)
    status = Column(String)
    sla_type = Column(String)
    distance_km = Column(Float)
    fuel_consumed = Column(Float)
    idle_time_min = Column(Float)
    vehicle_condition = Column(String)
    origin_lat = Column(Float)
    origin_lng = Column(Float)
    dest_lat = Column(Float)
    dest_lng = Column(Float)
    estimated_time_min = Column(Float)
    actual_time_min = Column(Float)
    fuel_efficiency = Column(Float)
    estimated_fuel_cost = Column(Float)
    route_efficiency = Column(Float)
    traffic_index = Column(Float)
    sla_compliance = Column(Integer)
    delay_minutes = Column(Float)
    penalty_amount = Column(Float)
    weather_condition = Column(String)
    weather_severity = Column(String)
    temperature = Column(Float)
    humidity = Column(Integer)
    wind_speed = Column(Float)
    date = Column(DateTime)
    time_of_day = Column(String)
    day_of_week = Column(String)
    is_weekend = Column(Boolean)